# FutureGateway fgapiserver configurable values are placed here
#
# Author: Riccardo Bruno <riccardo.bruno@ct.infn.it>

# fgAPIServer WSGI engines:
# apache - Uses apache + mod_wsgi
# nginx  - nginx + uwsgi (not yet implemented)
fg_wsgieng: apache

# Values for apache settings (Deb/Ubuntu only)
apache_mods_enabled:
   - rewrite.load
   - ssl.load

fg_fgapiserver: |
                #!/bin/bash
                #
                # fgAPIServer Environment settings configuration file
                #
                # Very specific fgAPIServer service component environment must be set here
                #
                # Author: Riccardo Bruno <riccardo.bruno@ct.infn.it>

